// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dblayer

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	Commentid   int32
	Pageid      int32
	Userid      int32
	Createdat   pgtype.Timestamp
	Editedbool  bool
	Upvotes     int32
	Downvotes   int32
	Commentdata string
	Parentid    int32
}

type Page struct {
	Pageurl       string
	Pageid        int32
	Commentscount int32
	Createdat     pgtype.Timestamp
}

type User struct {
	Userid    int32
	Username  string
	Firstname string
	Lastname  string
	Emailid   string
}

type Userrelation struct {
	Vieweruserid    int32
	Commentoruserid int32
	Tag             string
	Positivity      bool
}
